// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Metadata struct {
	ServerId             int32    `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Region               string   `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Provider             string   `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	UserId               int64    `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpireAt             int64    `protobuf:"varint,5,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	Adult                int32    `protobuf:"varint,6,opt,name=adult,proto3" json:"adult,omitempty"`
	Addr                 string   `protobuf:"bytes,7,opt,name=addr,proto3" json:"addr,omitempty"`
	Model                string   `protobuf:"bytes,8,opt,name=model,proto3" json:"model,omitempty"`
	CryptoSeed           string   `protobuf:"bytes,9,opt,name=crypto_seed,json=cryptoSeed,proto3" json:"crypto_seed,omitempty"`
	ClientVersion        string   `protobuf:"bytes,10,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *Metadata) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *Metadata) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *Metadata) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Metadata) GetExpireAt() int64 {
	if m != nil {
		return m.ExpireAt
	}
	return 0
}

func (m *Metadata) GetAdult() int32 {
	if m != nil {
		return m.Adult
	}
	return 0
}

func (m *Metadata) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *Metadata) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *Metadata) GetCryptoSeed() string {
	if m != nil {
		return m.CryptoSeed
	}
	return ""
}

func (m *Metadata) GetClientVersion() string {
	if m != nil {
		return m.ClientVersion
	}
	return ""
}

type KeyValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (m *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(m, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type IdValue struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Value                int32    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdValue) Reset()         { *m = IdValue{} }
func (m *IdValue) String() string { return proto.CompactTextString(m) }
func (*IdValue) ProtoMessage()    {}
func (*IdValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *IdValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdValue.Unmarshal(m, b)
}
func (m *IdValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdValue.Marshal(b, m, deterministic)
}
func (m *IdValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdValue.Merge(m, src)
}
func (m *IdValue) XXX_Size() int {
	return xxx_messageInfo_IdValue.Size(m)
}
func (m *IdValue) XXX_DiscardUnknown() {
	xxx_messageInfo_IdValue.DiscardUnknown(m)
}

var xxx_messageInfo_IdValue proto.InternalMessageInfo

func (m *IdValue) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *IdValue) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type KVPair struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                int32    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KVPair) Reset()         { *m = KVPair{} }
func (m *KVPair) String() string { return proto.CompactTextString(m) }
func (*KVPair) ProtoMessage()    {}
func (*KVPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

func (m *KVPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KVPair.Unmarshal(m, b)
}
func (m *KVPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KVPair.Marshal(b, m, deterministic)
}
func (m *KVPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVPair.Merge(m, src)
}
func (m *KVPair) XXX_Size() int {
	return xxx_messageInfo_KVPair.Size(m)
}
func (m *KVPair) XXX_DiscardUnknown() {
	xxx_messageInfo_KVPair.DiscardUnknown(m)
}

var xxx_messageInfo_KVPair proto.InternalMessageInfo

func (m *KVPair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KVPair) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type TypeData struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Data                 int32    `protobuf:"varint,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TypeData) Reset()         { *m = TypeData{} }
func (m *TypeData) String() string { return proto.CompactTextString(m) }
func (*TypeData) ProtoMessage()    {}
func (*TypeData) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{4}
}

func (m *TypeData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeData.Unmarshal(m, b)
}
func (m *TypeData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeData.Marshal(b, m, deterministic)
}
func (m *TypeData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeData.Merge(m, src)
}
func (m *TypeData) XXX_Size() int {
	return xxx_messageInfo_TypeData.Size(m)
}
func (m *TypeData) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeData.DiscardUnknown(m)
}

var xxx_messageInfo_TypeData proto.InternalMessageInfo

func (m *TypeData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TypeData) GetData() int32 {
	if m != nil {
		return m.Data
	}
	return 0
}

// 道具同步结构
type Item struct {
	Tid                  int32    `protobuf:"varint,1,opt,name=tid,proto3" json:"tid,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Id                   int32    `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{5}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetTid() int32 {
	if m != nil {
		return m.Tid
	}
	return 0
}

func (m *Item) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Item) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Metadata)(nil), "proto.Metadata")
	proto.RegisterType((*KeyValue)(nil), "proto.KeyValue")
	proto.RegisterType((*IdValue)(nil), "proto.IdValue")
	proto.RegisterType((*KVPair)(nil), "proto.KVPair")
	proto.RegisterType((*TypeData)(nil), "proto.TypeData")
	proto.RegisterType((*Item)(nil), "proto.Item")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcd, 0x4a, 0xf4, 0x30,
	0x14, 0xa5, 0xbf, 0xd3, 0xde, 0xef, 0x9b, 0x41, 0x82, 0x68, 0xd0, 0x85, 0x43, 0x41, 0x98, 0x95,
	0xca, 0xb8, 0x17, 0x04, 0x37, 0x65, 0x10, 0xa4, 0xca, 0x6c, 0x4b, 0x6c, 0x2e, 0x12, 0x6c, 0x9b,
	0x92, 0xa6, 0xc5, 0x3e, 0x8a, 0x6f, 0x2b, 0x49, 0x3a, 0x03, 0xae, 0x5c, 0xf5, 0xfc, 0xe4, 0xf4,
	0xa4, 0xf7, 0x16, 0xfe, 0x57, 0xb2, 0x69, 0x64, 0x7b, 0xd3, 0x29, 0xa9, 0x25, 0x89, 0xec, 0x23,
	0xfb, 0xf6, 0x21, 0x79, 0x46, 0xcd, 0x38, 0xd3, 0x8c, 0x5c, 0x42, 0xda, 0xa3, 0x1a, 0x51, 0x95,
	0x82, 0x53, 0x6f, 0xed, 0x6d, 0xa2, 0x22, 0x71, 0x42, 0xce, 0xc9, 0x19, 0xc4, 0x0a, 0x3f, 0x84,
	0x6c, 0xa9, 0xbf, 0xf6, 0x36, 0x69, 0x31, 0x33, 0x72, 0x01, 0x49, 0xa7, 0xe4, 0x28, 0x38, 0x2a,
	0x1a, 0x58, 0xe7, 0xc8, 0xc9, 0x39, 0x2c, 0x86, 0xde, 0xbd, 0x2e, 0x5c, 0x7b, 0x9b, 0xa0, 0x88,
	0x0d, 0xcd, 0xb9, 0x69, 0xc2, 0xaf, 0x4e, 0x28, 0x2c, 0x99, 0xa6, 0x91, 0xb5, 0x12, 0x27, 0x3c,
	0x6a, 0x72, 0x0a, 0x11, 0xe3, 0x43, 0xad, 0x69, 0x6c, 0xaf, 0xe0, 0x08, 0x21, 0x10, 0x32, 0xce,
	0x15, 0x5d, 0xd8, 0x0e, 0x8b, 0xcd, 0xc9, 0x46, 0x72, 0xac, 0x69, 0x62, 0x45, 0x47, 0xc8, 0x15,
	0xfc, 0xab, 0xd4, 0xd4, 0x69, 0x59, 0xf6, 0x88, 0x9c, 0xa6, 0xd6, 0x03, 0x27, 0xbd, 0x22, 0x72,
	0x72, 0x0d, 0xab, 0xaa, 0x16, 0xd8, 0xea, 0x72, 0x44, 0xd5, 0x9b, 0x4f, 0x02, 0x7b, 0x66, 0xe9,
	0xd4, 0xbd, 0x13, 0xb3, 0x2d, 0x24, 0x3b, 0x9c, 0xf6, 0xac, 0x1e, 0x90, 0x9c, 0x40, 0xf0, 0x89,
	0x93, 0x1d, 0x4a, 0x5a, 0x18, 0x68, 0xba, 0x47, 0x63, 0xcd, 0xe3, 0x70, 0x24, 0xbb, 0x85, 0x45,
	0xce, 0x5d, 0x64, 0x05, 0xfe, 0x3c, 0xc6, 0x65, 0xe1, 0x0b, 0xfe, 0x3b, 0x10, 0x1d, 0x02, 0x77,
	0x10, 0xef, 0xf6, 0x2f, 0x4c, 0xa8, 0xbf, 0x2a, 0x8e, 0x89, 0x2d, 0x24, 0x6f, 0x53, 0x87, 0x4f,
	0x66, 0x63, 0x04, 0x42, 0x3d, 0x75, 0x38, 0x87, 0x2c, 0x36, 0x9a, 0xd9, 0xe6, 0x1c, 0xb2, 0x38,
	0x7b, 0x80, 0x30, 0xd7, 0xd8, 0x98, 0x0e, 0x7d, 0xdc, 0xad, 0x81, 0xa6, 0xa3, 0x92, 0x43, 0xab,
	0x0f, 0x1d, 0x96, 0xcc, 0x77, 0x0f, 0xac, 0xe4, 0x0b, 0xfe, 0x1e, 0xdb, 0xbf, 0xe5, 0xfe, 0x27,
	0x00, 0x00, 0xff, 0xff, 0x77, 0x29, 0xe5, 0xad, 0x44, 0x02, 0x00, 0x00,
}
