// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dbstruct.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CharBase struct {
	Version              string    `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ServerId             int32     `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Channel              string    `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	LastIp               string    `protobuf:"bytes,4,opt,name=last_ip,json=lastIp,proto3" json:"last_ip,omitempty"`
	UserId               uint32    `protobuf:"varint,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Provider             string    `protobuf:"bytes,8,opt,name=provider,proto3" json:"provider,omitempty"`
	Region               string    `protobuf:"bytes,9,opt,name=region,proto3" json:"region,omitempty"`
	Adult                int32     `protobuf:"varint,10,opt,name=adult,proto3" json:"adult,omitempty"`
	Id                   uint32    `protobuf:"varint,11,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string    `protobuf:"bytes,12,opt,name=name,proto3" json:"name,omitempty"`
	Level                int32     `protobuf:"varint,13,opt,name=level,proto3" json:"level,omitempty"`
	CreateAt             int64     `protobuf:"varint,31,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	OnlineAt             int64     `protobuf:"varint,32,opt,name=online_at,json=onlineAt,proto3" json:"online_at,omitempty"`
	OfflineAt            int64     `protobuf:"varint,33,opt,name=offline_at,json=offlineAt,proto3" json:"offline_at,omitempty"`
	TotalOnline          int64     `protobuf:"varint,34,opt,name=total_online,json=totalOnline,proto3" json:"total_online,omitempty"`
	Item                 *ItemSave `protobuf:"bytes,50,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CharBase) Reset()         { *m = CharBase{} }
func (m *CharBase) String() string { return proto.CompactTextString(m) }
func (*CharBase) ProtoMessage()    {}
func (*CharBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_d15ca51d71956786, []int{0}
}

func (m *CharBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CharBase.Unmarshal(m, b)
}
func (m *CharBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CharBase.Marshal(b, m, deterministic)
}
func (m *CharBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CharBase.Merge(m, src)
}
func (m *CharBase) XXX_Size() int {
	return xxx_messageInfo_CharBase.Size(m)
}
func (m *CharBase) XXX_DiscardUnknown() {
	xxx_messageInfo_CharBase.DiscardUnknown(m)
}

var xxx_messageInfo_CharBase proto.InternalMessageInfo

func (m *CharBase) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *CharBase) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *CharBase) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *CharBase) GetLastIp() string {
	if m != nil {
		return m.LastIp
	}
	return ""
}

func (m *CharBase) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CharBase) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *CharBase) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *CharBase) GetAdult() int32 {
	if m != nil {
		return m.Adult
	}
	return 0
}

func (m *CharBase) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CharBase) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CharBase) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *CharBase) GetCreateAt() int64 {
	if m != nil {
		return m.CreateAt
	}
	return 0
}

func (m *CharBase) GetOnlineAt() int64 {
	if m != nil {
		return m.OnlineAt
	}
	return 0
}

func (m *CharBase) GetOfflineAt() int64 {
	if m != nil {
		return m.OfflineAt
	}
	return 0
}

func (m *CharBase) GetTotalOnline() int64 {
	if m != nil {
		return m.TotalOnline
	}
	return 0
}

func (m *CharBase) GetItem() *ItemSave {
	if m != nil {
		return m.Item
	}
	return nil
}

type ItemSave struct {
	Items                *Item    `protobuf:"bytes,1,opt,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemSave) Reset()         { *m = ItemSave{} }
func (m *ItemSave) String() string { return proto.CompactTextString(m) }
func (*ItemSave) ProtoMessage()    {}
func (*ItemSave) Descriptor() ([]byte, []int) {
	return fileDescriptor_d15ca51d71956786, []int{1}
}

func (m *ItemSave) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemSave.Unmarshal(m, b)
}
func (m *ItemSave) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemSave.Marshal(b, m, deterministic)
}
func (m *ItemSave) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemSave.Merge(m, src)
}
func (m *ItemSave) XXX_Size() int {
	return xxx_messageInfo_ItemSave.Size(m)
}
func (m *ItemSave) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemSave.DiscardUnknown(m)
}

var xxx_messageInfo_ItemSave proto.InternalMessageInfo

func (m *ItemSave) GetItems() *Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*CharBase)(nil), "proto.CharBase")
	proto.RegisterType((*ItemSave)(nil), "proto.ItemSave")
}

func init() { proto.RegisterFile("dbstruct.proto", fileDescriptor_d15ca51d71956786) }

var fileDescriptor_d15ca51d71956786 = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x41, 0x6e, 0xab, 0x30,
	0x10, 0x86, 0x45, 0x12, 0x08, 0x0c, 0x49, 0x9e, 0x64, 0x3d, 0xb5, 0x56, 0xaa, 0xaa, 0x24, 0xdd,
	0xb0, 0x69, 0x16, 0xe9, 0x09, 0xd2, 0xae, 0x58, 0x55, 0xa2, 0x07, 0x40, 0x0e, 0x9e, 0x34, 0x96,
	0x00, 0x23, 0xe3, 0x70, 0xb0, 0x9e, 0xb0, 0xf2, 0x38, 0xa9, 0xba, 0x82, 0xff, 0xfb, 0xf8, 0x47,
	0x83, 0x06, 0x56, 0xf2, 0x38, 0x58, 0x73, 0xa9, 0xed, 0xae, 0x37, 0xda, 0x6a, 0x16, 0xd2, 0x63,
	0xbd, 0xa8, 0x75, 0xdb, 0xea, 0xce, 0xc3, 0xed, 0xf7, 0x14, 0xe2, 0xf7, 0xb3, 0x30, 0x6f, 0x62,
	0x40, 0xc6, 0x61, 0x3e, 0xa2, 0x19, 0x94, 0xee, 0x78, 0x90, 0x05, 0x79, 0x52, 0xde, 0x22, 0x7b,
	0x80, 0x64, 0x40, 0x33, 0xa2, 0xa9, 0x94, 0xe4, 0x93, 0x2c, 0xc8, 0xc3, 0x32, 0xf6, 0xa0, 0x90,
	0xae, 0x56, 0x9f, 0x45, 0xd7, 0x61, 0xc3, 0xa7, 0xbe, 0x76, 0x8d, 0xec, 0x1e, 0xe6, 0x8d, 0x18,
	0x6c, 0xa5, 0x7a, 0x3e, 0x23, 0x13, 0xb9, 0x58, 0xf4, 0x4e, 0x5c, 0x06, 0x3f, 0x2d, 0xca, 0x82,
	0x7c, 0x59, 0x46, 0x2e, 0x16, 0x92, 0xad, 0x21, 0xee, 0x8d, 0x1e, 0x95, 0x44, 0xc3, 0x63, 0xaa,
	0xfc, 0x66, 0x76, 0x07, 0x91, 0xc1, 0x2f, 0xb7, 0x5d, 0xe2, 0x87, 0xf9, 0xc4, 0xfe, 0x43, 0x28,
	0xe4, 0xa5, 0xb1, 0x1c, 0x68, 0x31, 0x1f, 0xd8, 0x0a, 0x26, 0x4a, 0xf2, 0x94, 0xa6, 0x4f, 0x94,
	0x64, 0x0c, 0x66, 0x9d, 0x68, 0x91, 0x2f, 0xa8, 0x4b, 0xef, 0xae, 0xd9, 0xe0, 0x88, 0x0d, 0x5f,
	0xfa, 0x26, 0x05, 0xf7, 0xb3, 0xb5, 0x41, 0x61, 0xb1, 0x12, 0x96, 0x3f, 0x65, 0x41, 0x3e, 0x2d,
	0x63, 0x0f, 0x0e, 0xd6, 0x49, 0xdd, 0x35, 0xaa, 0x23, 0x99, 0x79, 0xe9, 0xc1, 0xc1, 0xb2, 0x47,
	0x00, 0x7d, 0x3a, 0xdd, 0xec, 0x86, 0x6c, 0x72, 0x25, 0x07, 0xcb, 0x36, 0xb0, 0xb0, 0xda, 0x8a,
	0xa6, 0xf2, 0x05, 0xbe, 0xa5, 0x0f, 0x52, 0x62, 0x1f, 0x84, 0xd8, 0x33, 0xcc, 0x94, 0xc5, 0x96,
	0xef, 0xb3, 0x20, 0x4f, 0xf7, 0xff, 0xfc, 0x95, 0x76, 0x85, 0xc5, 0xf6, 0x53, 0x8c, 0x58, 0x92,
	0xdc, 0xbe, 0x40, 0x7c, 0x23, 0x6c, 0x03, 0xa1, 0x63, 0x03, 0x5d, 0x2c, 0xdd, 0xa7, 0x7f, 0x1a,
	0xa5, 0x37, 0xc7, 0x88, 0xd0, 0xeb, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x41, 0xe8, 0x5c, 0xa4,
	0x11, 0x02, 0x00, 0x00,
}
