// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Ping 服务器的消息
type PingC2S struct {
	ReqId  uint64 `protobuf:"varint,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	UserId int64  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	//	uint32 time    = 1;
	SerList              string   `protobuf:"bytes,3,opt,name=ser_list,json=serList,proto3" json:"ser_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingC2S) Reset()         { *m = PingC2S{} }
func (m *PingC2S) String() string { return proto.CompactTextString(m) }
func (*PingC2S) ProtoMessage()    {}
func (*PingC2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{0}
}

func (m *PingC2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingC2S.Unmarshal(m, b)
}
func (m *PingC2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingC2S.Marshal(b, m, deterministic)
}
func (m *PingC2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingC2S.Merge(m, src)
}
func (m *PingC2S) XXX_Size() int {
	return xxx_messageInfo_PingC2S.Size(m)
}
func (m *PingC2S) XXX_DiscardUnknown() {
	xxx_messageInfo_PingC2S.DiscardUnknown(m)
}

var xxx_messageInfo_PingC2S proto.InternalMessageInfo

func (m *PingC2S) GetReqId() uint64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func (m *PingC2S) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PingC2S) GetSerList() string {
	if m != nil {
		return m.SerList
	}
	return ""
}

type PingS2C struct {
	//	uint32 time    = 1;
	//	int64 user_id = 2;
	//	int32 randint = 3;
	ReplyId              uint64   `protobuf:"varint,1,opt,name=reply_id,json=replyId,proto3" json:"reply_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SerList              string   `protobuf:"bytes,3,opt,name=ser_list,json=serList,proto3" json:"ser_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingS2C) Reset()         { *m = PingS2C{} }
func (m *PingS2C) String() string { return proto.CompactTextString(m) }
func (*PingS2C) ProtoMessage()    {}
func (*PingS2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{1}
}

func (m *PingS2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingS2C.Unmarshal(m, b)
}
func (m *PingS2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingS2C.Marshal(b, m, deterministic)
}
func (m *PingS2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingS2C.Merge(m, src)
}
func (m *PingS2C) XXX_Size() int {
	return xxx_messageInfo_PingS2C.Size(m)
}
func (m *PingS2C) XXX_DiscardUnknown() {
	xxx_messageInfo_PingS2C.DiscardUnknown(m)
}

var xxx_messageInfo_PingS2C proto.InternalMessageInfo

func (m *PingS2C) GetReplyId() uint64 {
	if m != nil {
		return m.ReplyId
	}
	return 0
}

func (m *PingS2C) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PingS2C) GetSerList() string {
	if m != nil {
		return m.SerList
	}
	return ""
}

type LoginC2S struct {
	ReqId                uint64   `protobuf:"varint,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SerList              string   `protobuf:"bytes,3,opt,name=ser_list,json=serList,proto3" json:"ser_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginC2S) Reset()         { *m = LoginC2S{} }
func (m *LoginC2S) String() string { return proto.CompactTextString(m) }
func (*LoginC2S) ProtoMessage()    {}
func (*LoginC2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{2}
}

func (m *LoginC2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginC2S.Unmarshal(m, b)
}
func (m *LoginC2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginC2S.Marshal(b, m, deterministic)
}
func (m *LoginC2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginC2S.Merge(m, src)
}
func (m *LoginC2S) XXX_Size() int {
	return xxx_messageInfo_LoginC2S.Size(m)
}
func (m *LoginC2S) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginC2S.DiscardUnknown(m)
}

var xxx_messageInfo_LoginC2S proto.InternalMessageInfo

func (m *LoginC2S) GetReqId() uint64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func (m *LoginC2S) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LoginC2S) GetSerList() string {
	if m != nil {
		return m.SerList
	}
	return ""
}

type LoginS2C struct {
	ReplyId              uint64   `protobuf:"varint,1,opt,name=reply_id,json=replyId,proto3" json:"reply_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SerList              string   `protobuf:"bytes,3,opt,name=ser_list,json=serList,proto3" json:"ser_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginS2C) Reset()         { *m = LoginS2C{} }
func (m *LoginS2C) String() string { return proto.CompactTextString(m) }
func (*LoginS2C) ProtoMessage()    {}
func (*LoginS2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{3}
}

func (m *LoginS2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginS2C.Unmarshal(m, b)
}
func (m *LoginS2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginS2C.Marshal(b, m, deterministic)
}
func (m *LoginS2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginS2C.Merge(m, src)
}
func (m *LoginS2C) XXX_Size() int {
	return xxx_messageInfo_LoginS2C.Size(m)
}
func (m *LoginS2C) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginS2C.DiscardUnknown(m)
}

var xxx_messageInfo_LoginS2C proto.InternalMessageInfo

func (m *LoginS2C) GetReplyId() uint64 {
	if m != nil {
		return m.ReplyId
	}
	return 0
}

func (m *LoginS2C) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LoginS2C) GetSerList() string {
	if m != nil {
		return m.SerList
	}
	return ""
}

type IntoGameC2S struct {
	ReqId                uint64   `protobuf:"varint,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SerList              string   `protobuf:"bytes,3,opt,name=ser_list,json=serList,proto3" json:"ser_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntoGameC2S) Reset()         { *m = IntoGameC2S{} }
func (m *IntoGameC2S) String() string { return proto.CompactTextString(m) }
func (*IntoGameC2S) ProtoMessage()    {}
func (*IntoGameC2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{4}
}

func (m *IntoGameC2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntoGameC2S.Unmarshal(m, b)
}
func (m *IntoGameC2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntoGameC2S.Marshal(b, m, deterministic)
}
func (m *IntoGameC2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntoGameC2S.Merge(m, src)
}
func (m *IntoGameC2S) XXX_Size() int {
	return xxx_messageInfo_IntoGameC2S.Size(m)
}
func (m *IntoGameC2S) XXX_DiscardUnknown() {
	xxx_messageInfo_IntoGameC2S.DiscardUnknown(m)
}

var xxx_messageInfo_IntoGameC2S proto.InternalMessageInfo

func (m *IntoGameC2S) GetReqId() uint64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func (m *IntoGameC2S) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *IntoGameC2S) GetSerList() string {
	if m != nil {
		return m.SerList
	}
	return ""
}

type IntoGameS2C struct {
	ReplyId              uint64   `protobuf:"varint,1,opt,name=reply_id,json=replyId,proto3" json:"reply_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SerList              string   `protobuf:"bytes,3,opt,name=ser_list,json=serList,proto3" json:"ser_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntoGameS2C) Reset()         { *m = IntoGameS2C{} }
func (m *IntoGameS2C) String() string { return proto.CompactTextString(m) }
func (*IntoGameS2C) ProtoMessage()    {}
func (*IntoGameS2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{5}
}

func (m *IntoGameS2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntoGameS2C.Unmarshal(m, b)
}
func (m *IntoGameS2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntoGameS2C.Marshal(b, m, deterministic)
}
func (m *IntoGameS2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntoGameS2C.Merge(m, src)
}
func (m *IntoGameS2C) XXX_Size() int {
	return xxx_messageInfo_IntoGameS2C.Size(m)
}
func (m *IntoGameS2C) XXX_DiscardUnknown() {
	xxx_messageInfo_IntoGameS2C.DiscardUnknown(m)
}

var xxx_messageInfo_IntoGameS2C proto.InternalMessageInfo

func (m *IntoGameS2C) GetReplyId() uint64 {
	if m != nil {
		return m.ReplyId
	}
	return 0
}

func (m *IntoGameS2C) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *IntoGameS2C) GetSerList() string {
	if m != nil {
		return m.SerList
	}
	return ""
}

func init() {
	proto.RegisterType((*PingC2S)(nil), "proto.PingC2S")
	proto.RegisterType((*PingS2C)(nil), "proto.PingS2C")
	proto.RegisterType((*LoginC2S)(nil), "proto.LoginC2S")
	proto.RegisterType((*LoginS2C)(nil), "proto.LoginS2C")
	proto.RegisterType((*IntoGameC2S)(nil), "proto.IntoGameC2S")
	proto.RegisterType((*IntoGameS2C)(nil), "proto.IntoGameS2C")
}

func init() { proto.RegisterFile("game.proto", fileDescriptor_38fc58335341d769) }

var fileDescriptor_38fc58335341d769 = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4f, 0xcc, 0x4d,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x21, 0x5c, 0xec, 0x01, 0x99,
	0x79, 0xe9, 0xce, 0x46, 0xc1, 0x42, 0xa2, 0x5c, 0x6c, 0x45, 0xa9, 0x85, 0xf1, 0x99, 0x29, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x2c, 0x41, 0xac, 0x45, 0xa9, 0x85, 0x9e, 0x29, 0x42, 0xe2, 0x5c, 0xec,
	0xa5, 0xc5, 0xa9, 0x45, 0x20, 0x71, 0x26, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0x36, 0x10, 0xd7, 0x33,
	0x45, 0x48, 0x92, 0x8b, 0x03, 0x24, 0x9e, 0x93, 0x59, 0x5c, 0x22, 0xc1, 0xac, 0xc0, 0xa8, 0xc1,
	0x19, 0xc4, 0x5e, 0x9c, 0x5a, 0xe4, 0x93, 0x59, 0x5c, 0xa2, 0x14, 0x01, 0x31, 0x35, 0xd8, 0xc8,
	0x19, 0xa4, 0xaa, 0x28, 0xb5, 0x20, 0xa7, 0x12, 0x61, 0x2e, 0x3b, 0x98, 0x4f, 0xa6, 0xc9, 0xa1,
	0x5c, 0x1c, 0x3e, 0xf9, 0xe9, 0x99, 0x79, 0x54, 0x76, 0x70, 0x24, 0xd4, 0x58, 0x1a, 0xb8, 0x38,
	0x82, 0x8b, 0xdb, 0x33, 0xaf, 0x24, 0xdf, 0x3d, 0x31, 0x37, 0x95, 0xca, 0x8e, 0x8e, 0x41, 0x98,
	0x4c, 0x7d, 0x77, 0x27, 0xb1, 0x81, 0x13, 0x88, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x37,
	0xfb, 0xb0, 0x35, 0x02, 0x00, 0x00,
}
