// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Category int32

const (
	Category_NONE  Category = 0
	Category_AGENT Category = 1
	Category_GAME  Category = 2
)

var Category_name = map[int32]string{
	0: "NONE",
	1: "AGENT",
	2: "GAME",
}

var Category_value = map[string]int32{
	"NONE":  0,
	"AGENT": 1,
	"GAME":  2,
}

func (x Category) String() string {
	return proto.EnumName(Category_name, int32(x))
}

func (Category) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0}
}

type CloseC2S struct {
	Code                 Errors   `protobuf:"varint,1,opt,name=code,proto3,enum=proto.Errors" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseC2S) Reset()         { *m = CloseC2S{} }
func (m *CloseC2S) String() string { return proto.CompactTextString(m) }
func (*CloseC2S) ProtoMessage()    {}
func (*CloseC2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0}
}

func (m *CloseC2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseC2S.Unmarshal(m, b)
}
func (m *CloseC2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseC2S.Marshal(b, m, deterministic)
}
func (m *CloseC2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseC2S.Merge(m, src)
}
func (m *CloseC2S) XXX_Size() int {
	return xxx_messageInfo_CloseC2S.Size(m)
}
func (m *CloseC2S) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseC2S.DiscardUnknown(m)
}

var xxx_messageInfo_CloseC2S proto.InternalMessageInfo

func (m *CloseC2S) GetCode() Errors {
	if m != nil {
		return m.Code
	}
	return Errors_OK
}

type CloseS2C struct {
	Code                 Errors   `protobuf:"varint,1,opt,name=code,proto3,enum=proto.Errors" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseS2C) Reset()         { *m = CloseS2C{} }
func (m *CloseS2C) String() string { return proto.CompactTextString(m) }
func (*CloseS2C) ProtoMessage()    {}
func (*CloseS2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{1}
}

func (m *CloseS2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseS2C.Unmarshal(m, b)
}
func (m *CloseS2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseS2C.Marshal(b, m, deterministic)
}
func (m *CloseS2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseS2C.Merge(m, src)
}
func (m *CloseS2C) XXX_Size() int {
	return xxx_messageInfo_CloseS2C.Size(m)
}
func (m *CloseS2C) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseS2C.DiscardUnknown(m)
}

var xxx_messageInfo_CloseS2C proto.InternalMessageInfo

func (m *CloseS2C) GetCode() Errors {
	if m != nil {
		return m.Code
	}
	return Errors_OK
}

type Request struct {
	// Types that are valid to be assigned to Msg:
	//	*Request_Close
	//	*Request_Ping
	//	*Request_Login
	//	*Request_IntoGame
	Msg                  isRequest_Msg `protobuf_oneof:"msg"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type isRequest_Msg interface {
	isRequest_Msg()
}

type Request_Close struct {
	Close *CloseC2S `protobuf:"bytes,99,opt,name=close,proto3,oneof"`
}

type Request_Ping struct {
	Ping *PingC2S `protobuf:"bytes,100,opt,name=ping,proto3,oneof"`
}

type Request_Login struct {
	Login *LoginC2S `protobuf:"bytes,101,opt,name=login,proto3,oneof"`
}

type Request_IntoGame struct {
	IntoGame *IntoGameC2S `protobuf:"bytes,102,opt,name=intoGame,proto3,oneof"`
}

func (*Request_Close) isRequest_Msg() {}

func (*Request_Ping) isRequest_Msg() {}

func (*Request_Login) isRequest_Msg() {}

func (*Request_IntoGame) isRequest_Msg() {}

func (m *Request) GetMsg() isRequest_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *Request) GetClose() *CloseC2S {
	if x, ok := m.GetMsg().(*Request_Close); ok {
		return x.Close
	}
	return nil
}

func (m *Request) GetPing() *PingC2S {
	if x, ok := m.GetMsg().(*Request_Ping); ok {
		return x.Ping
	}
	return nil
}

func (m *Request) GetLogin() *LoginC2S {
	if x, ok := m.GetMsg().(*Request_Login); ok {
		return x.Login
	}
	return nil
}

func (m *Request) GetIntoGame() *IntoGameC2S {
	if x, ok := m.GetMsg().(*Request_IntoGame); ok {
		return x.IntoGame
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Request) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Request_Close)(nil),
		(*Request_Ping)(nil),
		(*Request_Login)(nil),
		(*Request_IntoGame)(nil),
	}
}

type Response struct {
	// Types that are valid to be assigned to Msg:
	//	*Response_Close
	//	*Response_Ping
	//	*Response_Login
	//	*Response_IntoGame
	Msg                  isResponse_Msg `protobuf_oneof:"msg"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type isResponse_Msg interface {
	isResponse_Msg()
}

type Response_Close struct {
	Close *CloseS2C `protobuf:"bytes,10099,opt,name=close,proto3,oneof"`
}

type Response_Ping struct {
	Ping *PingS2C `protobuf:"bytes,10100,opt,name=ping,proto3,oneof"`
}

type Response_Login struct {
	Login *LoginS2C `protobuf:"bytes,10101,opt,name=login,proto3,oneof"`
}

type Response_IntoGame struct {
	IntoGame *IntoGameS2C `protobuf:"bytes,10102,opt,name=intoGame,proto3,oneof"`
}

func (*Response_Close) isResponse_Msg() {}

func (*Response_Ping) isResponse_Msg() {}

func (*Response_Login) isResponse_Msg() {}

func (*Response_IntoGame) isResponse_Msg() {}

func (m *Response) GetMsg() isResponse_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *Response) GetClose() *CloseS2C {
	if x, ok := m.GetMsg().(*Response_Close); ok {
		return x.Close
	}
	return nil
}

func (m *Response) GetPing() *PingS2C {
	if x, ok := m.GetMsg().(*Response_Ping); ok {
		return x.Ping
	}
	return nil
}

func (m *Response) GetLogin() *LoginS2C {
	if x, ok := m.GetMsg().(*Response_Login); ok {
		return x.Login
	}
	return nil
}

func (m *Response) GetIntoGame() *IntoGameS2C {
	if x, ok := m.GetMsg().(*Response_IntoGame); ok {
		return x.IntoGame
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Response) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Response_Close)(nil),
		(*Response_Ping)(nil),
		(*Response_Login)(nil),
		(*Response_IntoGame)(nil),
	}
}

func init() {
	proto.RegisterEnum("proto.Category", Category_name, Category_value)
	proto.RegisterType((*CloseC2S)(nil), "proto.CloseC2S")
	proto.RegisterType((*CloseS2C)(nil), "proto.CloseS2C")
	proto.RegisterType((*Request)(nil), "proto.Request")
	proto.RegisterType((*Response)(nil), "proto.Response")
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor_2bc2336598a3f7e0) }

var fileDescriptor_2bc2336598a3f7e0 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x8f, 0xcb, 0x4e, 0xb4, 0x30,
	0x1c, 0xc5, 0xa7, 0xdf, 0x07, 0x8a, 0xff, 0x89, 0x48, 0xba, 0x22, 0xb3, 0x1a, 0x27, 0x1a, 0xd1,
	0xc4, 0x89, 0xe2, 0x13, 0x8c, 0x84, 0xa0, 0x89, 0x56, 0x03, 0xbe, 0x00, 0x32, 0xb5, 0x21, 0x01,
	0x8a, 0x14, 0x17, 0xbe, 0x9a, 0x1b, 0x1f, 0xca, 0xcb, 0xda, 0xd0, 0x96, 0xf1, 0x82, 0x0b, 0x57,
	0xd0, 0x73, 0x7e, 0x3d, 0x3d, 0x07, 0xec, 0xba, 0xe1, 0x2d, 0xcf, 0x78, 0x31, 0x97, 0x3f, 0xd8,
	0x94, 0x9f, 0x09, 0xb0, 0xb4, 0xa4, 0x4a, 0x9a, 0x8c, 0x69, 0xd3, 0xf0, 0x46, 0x1d, 0x66, 0x87,
	0x60, 0x05, 0x05, 0x17, 0x34, 0xf0, 0x13, 0xbc, 0x0d, 0x46, 0xc6, 0x97, 0xd4, 0x45, 0x53, 0xe4,
	0xd9, 0xfe, 0xa6, 0x22, 0xe6, 0x61, 0x47, 0x8b, 0x58, 0x5a, 0x2b, 0x3c, 0xf1, 0x83, 0xbf, 0xe0,
	0x4f, 0x08, 0xd6, 0x63, 0x7a, 0xff, 0x40, 0x45, 0x8b, 0xf7, 0xc0, 0xcc, 0xba, 0xab, 0x6e, 0x36,
	0x45, 0xde, 0xd8, 0xdf, 0xd2, 0x7c, 0xff, 0xfa, 0xd9, 0x28, 0x56, 0x3e, 0xde, 0x01, 0xa3, 0xce,
	0x2b, 0xe6, 0x2e, 0x25, 0x67, 0x6b, 0xee, 0x3a, 0xaf, 0x98, 0xc2, 0xa4, 0xdb, 0xc5, 0x15, 0x9c,
	0xe5, 0x95, 0x4b, 0xbf, 0xc5, 0x5d, 0x74, 0x9a, 0x8e, 0x93, 0x3e, 0x3e, 0x02, 0x2b, 0xaf, 0x5a,
	0x1e, 0xa5, 0x25, 0x75, 0xef, 0x24, 0x8b, 0x35, 0x7b, 0xae, 0x65, 0x85, 0xaf, 0xa8, 0x53, 0x13,
	0xfe, 0x97, 0x82, 0xcd, 0x9e, 0x11, 0x58, 0x31, 0x15, 0x35, 0xaf, 0x04, 0xc5, 0x5e, 0xdf, 0xfe,
	0x85, 0x0c, 0xeb, 0x27, 0x7e, 0xf0, 0x59, 0x7f, 0x57, 0xd7, 0x7f, 0x25, 0x83, 0xfe, 0x8a, 0x53,
	0xfd, 0xbd, 0xbe, 0xff, 0x1b, 0x19, 0x0e, 0xd0, 0x81, 0x6a, 0xc0, 0xf1, 0x97, 0x01, 0xef, 0xe4,
	0xd7, 0x05, 0x8a, 0xff, 0xb9, 0xe0, 0x60, 0x1f, 0xac, 0x20, 0x6d, 0x29, 0xe3, 0xcd, 0x23, 0xb6,
	0xc0, 0x20, 0x57, 0x24, 0x74, 0x46, 0x78, 0x03, 0xcc, 0x45, 0x14, 0x92, 0x1b, 0x07, 0x75, 0x62,
	0xb4, 0xb8, 0x0c, 0x9d, 0x7f, 0xb7, 0x6b, 0x32, 0xf0, 0xe4, 0x23, 0x00, 0x00, 0xff, 0xff, 0xf5,
	0x40, 0xb3, 0x67, 0x40, 0x02, 0x00, 0x00,
}
